# Generated by Django 5.2.6 on 2026-01-25 10:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='Logiciel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du logiciel')),
                ('version', models.CharField(max_length=50, verbose_name='Version')),
                ('editeur', models.CharField(blank=True, max_length=200, verbose_name='Éditeur')),
                ('categorie', models.CharField(choices=[('systeme', "Système d'exploitation"), ('bureautique', 'Bureautique'), ('graphique', 'Graphique'), ('programmation', 'Programmation'), ('securite', 'Sécurité'), ('gestion', 'Gestion'), ('autre', 'Autre')], default='bureautique', max_length=20, verbose_name='Catégorie')),
                ('licence', models.CharField(blank=True, max_length=100, verbose_name='Type de licence')),
                ('date_acquision', models.DateField(blank=True, null=True, verbose_name="Date d'acquisition")),
                ('cout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Logiciel',
                'verbose_name_plural': 'Logiciels',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profilutilisateur', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('departement', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('role', models.CharField(choices=[('user', 'Utilisateur standard'), ('technician', 'Technicien'), ('secretary', 'Secrétaire'), ('director', 'Directeur'), ('admin', 'Administrateur')], default='user', max_length=20)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('consultation', 'Consultation'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('autre', 'Autre')], max_length=20)),
                ('module', models.CharField(choices=[('materiel', 'Matériel'), ('logiciel', 'Logiciel'), ('installation_logiciel', 'Installation Logiciel'), ('reseau', 'Réseau'), ('incident', 'Incident'), ('alerte', 'Alerte'), ('reparation', 'Réparation'), ('fournisseur', 'Fournisseur'), ('profil_utilisateur', 'Profil Utilisateur'), ('utilisateur', 'Utilisateur'), ('dashboard', 'Tableau de bord'), ('rapport', 'Rapport'), ('systeme', 'Système')], max_length=30)),
                ('objet_id', models.IntegerField(blank=True, null=True)),
                ('objet_nom', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('date_action', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donnees_avant', models.JSONField(blank=True, null=True)),
                ('donnees_apres', models.JSONField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Historique d'action",
                'verbose_name_plural': "Historiques d'actions",
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nom du matériel')),
                ('reference', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Référence/Numéro de série')),
                ('date_achat', models.DateField(verbose_name="Date d'achat")),
                ('etat', models.CharField(choices=[('fonctionnel', 'Fonctionnel'), ('en_panne', 'En panne'), ('repare', 'Réparé'), ('obsolete', 'Obsolète'), ('en_maintenance', 'En maintenance'), ('en_amelioration', 'En amélioration'), ('en_reparation', 'En réparation'), ('hors_service', 'Hors service')], default='fonctionnel', max_length=20, verbose_name='État')),
                ('service_attribue', models.CharField(choices=[('Direction', 'Direction'), ('Comptabilité', 'Comptabilité'), ('Ressources Humaines', 'Ressources Humaines'), ('Informatique', 'Informatique'), ('Secrétariat', 'Secrétariat'), ('Archives', 'Archives')], max_length=50, verbose_name='Service attribué')),
                ('utilisateur_attribue', models.CharField(blank=True, max_length=100, null=True, verbose_name='Utilisateur attribué')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_parc.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Matériel',
                'verbose_name_plural': 'Matériels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstallationLogiciel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logiciel', models.CharField(max_length=200)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('date_installation', models.DateField(auto_now_add=True)),
                ('licence', models.CharField(blank=True, max_length=100)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_parc.materiel')),
            ],
            options={
                'verbose_name': 'Installation Logiciel',
                'verbose_name_plural': 'Installations Logiciels',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_incident', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('priorite', models.IntegerField(choices=[(1, 'Basse'), (2, 'Moyenne'), (3, 'Haute')], default=1)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours de traitement'), ('resolu', 'Résolu'), ('ferme', 'Fermé')], default='ouvert', max_length=20)),
                ('materiel_concerne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='gestion_parc.materiel')),
                ('utilisateur_reporteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_reportes', to='gestion_parc.utilisateur')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-date_incident'],
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('maintenance', 'Maintenance préventive requise'), ('panne', 'Risque de panne'), ('securite', 'Alerte de sécurité'), ('performance', 'Problème de performance'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_echeance', models.DateTimeField(blank=True, null=True)),
                ('traitee', models.BooleanField(default=False)),
                ('materiel_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='gestion_parc.materiel')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Reparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('type_reparation', models.CharField(choices=[('preventive', 'Préventive'), ('corrective', 'Corrective'), ('ameliorative', 'Améliorative')], max_length=20)),
                ('cout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('technicien_responsable', models.CharField(default='Technicien non spécifié', max_length=200, verbose_name='Technicien responsable')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reparations', to='gestion_parc.incident')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparations', to='gestion_parc.materiel')),
            ],
            options={
                'verbose_name': 'Réparation',
                'verbose_name_plural': 'Réparations',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Reseau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('adresse_mac', models.CharField(blank=True, max_length=17)),
                ('statut_connexion', models.BooleanField(default=True)),
                ('dernier_ping', models.DateTimeField(blank=True, null=True)),
                ('materiel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_parc.materiel')),
            ],
            options={
                'verbose_name': 'Réseau',
                'verbose_name_plural': 'Réseaux',
            },
        ),
    ]
