# Generated by Django 5.2.6 on 2025-11-17 16:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('type_fournisseur', models.CharField(choices=[('materiel', 'Matériel'), ('logiciel', 'Logiciel'), ('mixte', 'Mixte')], max_length=10)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='Logiciel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('editeur', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('type_logiciel', models.CharField(choices=[('os', 'Système d exploitation'), ('bureautique', 'Bureautique'), ('metier', 'Métier'), ('securite', 'Sécurité'), ('autre', 'Autre')], max_length=20)),
                ('date_installation', models.DateField(blank=True, null=True)),
                ('date_expiration_licence', models.DateField(blank=True, null=True)),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_parc.fournisseur')),
            ],
            options={
                'verbose_name': 'Logiciel',
                'verbose_name_plural': 'Logiciels',
            },
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nom du matériel')),
                ('reference', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Référence/Numéro de série')),
                ('date_achat', models.DateField(verbose_name="Date d'achat")),
                ('etat', models.CharField(choices=[('fonctionnel', 'Fonctionnel'), ('en_panne', 'En panne'), ('repare', 'Réparé'), ('obsolete', 'Obsolète')], default='fonctionnel', max_length=20, verbose_name='État')),
                ('service_attribue', models.CharField(choices=[('Direction', 'Direction'), ('Comptabilité', 'Comptabilité'), ('Ressources Humaines', 'Ressources Humaines'), ('Informatique', 'Informatique'), ('Secrétariat', 'Secrétariat'), ('Archives', 'Archives')], max_length=50, verbose_name='Service attribué')),
                ('utilisateur_attribue', models.CharField(blank=True, max_length=100, null=True, verbose_name='Utilisateur attribué')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_parc.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Matériel',
                'verbose_name_plural': 'Matériels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('priorite', models.CharField(choices=[('critique', 'Critique'), ('elevee', 'Élevée'), ('moyenne', 'Moyenne'), ('basse', 'Basse')], default='moyenne', max_length=20)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('ferme', 'Fermé')], default='ouvert', max_length=20)),
                ('type_incident', models.CharField(choices=[('materiel', 'Matériel'), ('logiciel', 'Logiciel'), ('reseau', 'Réseau'), ('mixte', 'Mixte')], max_length=20)),
                ('utilisateur_signaleur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('logiciel_concerne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_parc.logiciel')),
                ('materiel_concerne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_parc.materiel')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Reparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('type_reparation', models.CharField(choices=[('preventive', 'Préventive'), ('corrective', 'Corrective'), ('ameliorative', 'Améliorative')], max_length=20)),
                ('cout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_parc.incident')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_parc.materiel')),
            ],
            options={
                'verbose_name': 'Réparation',
                'verbose_name_plural': 'Réparations',
            },
        ),
        migrations.CreateModel(
            name='Reseau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_ip', models.GenericIPAddressField()),
                ('nom_hote', models.CharField(max_length=100)),
                ('sous_reseau', models.GenericIPAddressField()),
                ('passerelle', models.GenericIPAddressField()),
                ('type_equipement', models.CharField(choices=[('poste', 'Poste de travail'), ('serveur', 'Serveur'), ('imprimante', 'Imprimante'), ('switch', 'Switch'), ('routeur', 'Routeur')], max_length=20)),
                ('statut_connexion', models.CharField(choices=[('connecte', 'Connecté'), ('deconnecte', 'Déconnecté'), ('instable', 'Instable')], default='connecte', max_length=20)),
                ('materiel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_parc.materiel')),
            ],
            options={
                'verbose_name': 'Configuration réseau',
                'verbose_name_plural': 'Configurations réseau',
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='reseau_concerne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_parc.reseau'),
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_alerte', models.DateTimeField(auto_now_add=True)),
                ('type_alerte', models.CharField(choices=[('securite', 'Sécurité'), ('performance', 'Performance'), ('panne', 'Panne'), ('maintenance', 'Maintenance')], max_length=20)),
                ('severite', models.CharField(choices=[('critique', 'Critique'), ('elevee', 'Élevée'), ('moyenne', 'Moyenne'), ('basse', 'Basse')], default='moyenne', max_length=20)),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_traitement', 'En traitement'), ('resolue', 'Résolue')], default='nouvelle', max_length=20)),
                ('incident_lie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_parc.incident')),
                ('logiciel_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_parc.logiciel')),
                ('materiel_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_parc.materiel')),
                ('reseau_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_parc.reseau')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-date_alerte'],
            },
        ),
        migrations.CreateModel(
            name='InstallationLogiciel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_installation', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('desinstalle', 'Désinstallé'), ('en_erreur', 'En erreur')], default='actif', max_length=20)),
                ('logiciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_parc.logiciel')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_parc.materiel')),
            ],
            options={
                'verbose_name': 'Installation logiciel',
                'verbose_name_plural': 'Installations logiciels',
                'unique_together': {('materiel', 'logiciel')},
            },
        ),
    ]
