# Generated by Django 5.2.6 on 2025-11-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_parc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(choices=[('user', 'Utilisateur standard'), ('technician', 'Technicien'), ('secretary', 'Secrétaire'), ('director', 'Directeur'), ('admin', 'Administrateur')], default='user', max_length=20),
        ),
    ]
