# Generated by Django 5.2.6 on 2025-11-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_parc', '0002_profilutilisateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
