# Generated by Django 5.2.6 on 2026-01-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_parc', '0003_fournisseur_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationlogiciel',
            name='date_installation',
            field=models.DateField(),
        ),
    ]
